version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=iic2173t1

  app:
    build: .
    restart: always
    links:
      - postgres
    environment:
      - DATABASE_URL
      - SECRET_KEY
      - APP_SETTINGS
    ports:
      - 80:80
